// <auto-generated />
namespace MvcMovie.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddModelValidation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddModelValidation));
        
        string IMigrationMetadata.Id
        {
            get { return "201408141615158_AddModelValidation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
